### ISSUE TITLE
Add a License

### ISSUE THREAD

**Issue by MrSmoer** [StonedEdge/Retro-Lite-CM5#26]
Hi,
this is an amazing project and very impressive design work.
There is lots of complexity in the USB-C Port and Power management design and it would be nice to know whether you would be happy to let others use your design as a reference :)
You could just add a License to let people know about your opinions on that ^^
Have a nice day!

**Comment by StonedEdge** [comment]
Hi,

Yes, happy for people to use the design files for however they please.
