### ISSUE TITLE
[Suggestion] HID Controller (Use RP2040 over 32u4)

### ISSUE THREAD

**Issue by Xelus22** [StonedEdge/Retro-Lite-CM5#3]
Hey StonedEdge,

Not sure where this would be its not exactly an issue. But came across this cool project. 
Was just going to suggest using an RP2040 + eeprom chip or emulated EEPROM (in flash) since they're much faster and cheaper than the old outdated 32u4. 
Could potentially even use the GP2040-CE firmware for it https://github.com/OpenStickCommunity/GP2040-CE/

Good luck with the project 👍

**Comment by StonedEdge** [comment]
Funny, now you mention it, it is weird why I didn’t switch over to the RP2040 sooner :) The design is being ported over so I will probably move away from the 32u4. Cheaper & more IO, too. Plus more RAM :)
