### ISSUE TITLE
Radxa 10FHD DSI Display

### ISSUE THREAD

**Issue by pterodyne** [StonedEdge/Retro-Lite-CM5#35]
Im interested in using your carrier board to design around a tablet PC.  I have a Radxa FHD10 DSI display.  It appears as if it would be compatible from what I can tell, and uses a standard overlay available from Radxa.  Any thoughts before I endeavor down this path?  Ive denuded a Rockchip Rock 5C, but have 2xRadxaCM5 units.  They work great on CM4 carriers, but Im really wanting to use the DSI display for simplicity.  Dealing with HDMI cables is a PITA.  The Radxa carrier is far to large for my project.  Your carrier looks like it would be perfect.  

If you have the time, let me know if you think it would work.

**Comment by StonedEdge** [comment]
Sorry, not sure how this is related to our project, but please feel free to use whatever assets in the repository for your use case.
